from selenium.webdriver.common.by import By


class CreatePersonModalLocators:

    CREATE_NEW_PERSON_TEXT = (By.CSS_SELECTOR, "#rcDialogTitle0")
    UPLOAD_PHOTO = (By.XPATH, "//input[@accept='.png,.jpg,.jpeg']")
    UPLOAD_OTHER_CV = (By.XPATH, "//span[text()=' Upload file']")
    ENTER_AKVELON_CV = (By.CSS_SELECTOR, "#akvelon_cv")
    FIRST_NAME = (By.CSS_SELECTOR, "#first_name")
    LAST_NAME = (By.CSS_SELECTOR, "#last_name")
    MIDDLE_NAME = (By.CSS_SELECTOR, "#middle_name")
    RECRUITER = (By.CSS_SELECTOR, "#assigned_hr")
    ROLES = (By.CSS_SELECTOR, "#roles")
    OFFICE = (By.CSS_SELECTOR, "#office")
    COUNTRY = (By.CSS_SELECTOR, "#country-select-default")
    CITY = (By.CSS_SELECTOR, "#city-select-default")
    CONTEXT_COMMENT = (By.CSS_SELECTOR, "#comment")
    SALARY_TEXT = (By.XPATH, "//span[text()='Salary']")
    SALARY_ICON = (By.XPATH, "//span[@aria-label='eye']")
    FULL_SALARY = (By.CSS_SELECTOR, "#salaryInfoSalaryAmount")
    BENCH_SALARY = (By.CSS_SELECTOR, "#salaryInfoBenchSalaryAmount")
    SALARY_COMMENT = (By.CSS_SELECTOR, "#salaryInfoComment")
    ENGLISH_LEVEL = (By.CSS_SELECTOR, "#english_level")
    ENGLISH_COMMENT = (By.CSS_SELECTOR, "#english_comment")
    PRIMARY_SKILL = (By.CSS_SELECTOR, "#rc_select_5")
    PRIMARY_SKILL_GRADE = (By.CSS_SELECTOR, "#rc_select_6")
    CONFIRMED_SKILL_CHECKBOX = (By.CSS_SELECTOR, "#primary_skills_0_is_confirmed")
    ADD_PRIMARY_SKILL = (By.XPATH, "//span[text()='+ Add one more skill']")
    OTHER_SKILL = (By.CSS_SELECTOR, "#rc_select_7")
    RESIDENCE_COUNTRY = (By.CSS_SELECTOR, "#residence-country-select")
    RESIDENCE_TYPE = (By.CSS_SELECTOR, "#residence-type-select")
    ADD_RESIDENCE = (By.XPATH, "//span[text()='+ Add one more residence']")
    WANT_RELOCATE = (By.CSS_SELECTOR, "#relocation_desires")
    WANT_RELOCATE_COMMENT = (By.CSS_SELECTOR, "#relocation_comment")
    ADD_ONE_MORE_CONTACT = (By.XPATH, "//span[text()='+ Add one more contact']")
    CONTACT_TYPE = (By.CSS_SELECTOR, "#contacts_0_contact_type")
    CONTACT_VALUE = (By.CSS_SELECTOR, "#contacts_0_value")

    CREATE_PERSON_BUTTON = (By.XPATH, "//button[@form='PersonForm']")
    CANCEL_CREATE_PERSON_BUTTON = (By.XPATH, "/html/body/div[2]/div/div[2]/div/div[2]/div[3]/button[1]")

    CROSS_EXIT = (By.XPATH, "//span[text()='Cancel']")